version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'dominikks'
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
    groups:
      safe-npm-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
        exclude-patterns:
          - '@sveltejs/*'
          - 'svelte'
          - 'vite'
          - 'mdsvex'
          - 'typescript'
          - 'typescript-eslint'
      svelte-and-build-toolchain:
        patterns:
          - '@sveltejs/*'
          - 'svelte'
          - 'vite'
          - 'mdsvex'
          - 'typescript'
          - 'typescript-eslint'
        update-types:
          - 'minor'
          - 'patch'
      major-npm-updates:
        patterns:
          - '*'
        update-types:
          - 'major'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'dominikks'
    groups:
      github-actions:
        patterns:
          - '*'
